[package]
name = "crypto-server"
version = "0.1.0"
authors = ["Rajat Talwar <cuterajat26@gmail.com>"]

[dependencies]

gotham = "0.3.0"
gotham_derive = "0.3.0"
hyper = "0.12"
mime = "0.3"
serde = "1"
serde_derive = "1"
serde_json = "1"